name: release_docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Core
        id: docker_build_core
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/core/Dockerfile
          push: true
          tags: lhjnilsson/foreverbull_core:latest  
      -
        name: Client
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/client/Dockerfile
          push: true
          tags: lhjnilsson/foreverbull_client:latest
      -
        name: Zipline
        id: docker_build_zipline
        uses: docker/build-push-action@v2
        with:
          context: .
          src: src/zipline/Dockerfile
          push: true
          tags: lhjnilsson/foreverbull_zipline:latest 